stages:
  - deploy

variables:
  IMAGE: prom:$CI_COMMIT_REF_SLUG
  COMPOSE_TEST: docker-compose -p prom_$CI_COMMIT_REF_SLUG

deploy_beta:
  image: docker:latest
  before_script:
    - echo '$COMPOSE_TEST'
    - export PORT=$(./check.sh)
    - ifconfig
    - envsubst < deploy/site > /etc/nginx/sites-available/$CI_COMMIT_REF_SLUG
    - ln -sf /etc/nginx/sites-available/$CI_COMMIT_REF_SLUG /etc/nginx/sites-enabled/$CI_COMMIT_REF_SLUG
    - sudo systemctl reload nginx
  stage: deploy
  script:
    - $COMPOSE_TEST down
    - $COMPOSE_TEST up --build -d
