version: '2'

networks:
  monitoring:

services:
  grafana:
    restart: always
    image: grafana/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring
    ports:
      - ${PORT}:3000

  prometheus:
    restart: always
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    depends_on:
      - node-exporter
      - pull-container
    networks:
      - monitoring

  pushgateway:
    restart: always
    image: prom/pushgateway
    depends_on:
      - prometheus
    networks:
      - monitoring

  node-exporter:
    restart: always
    image: prom/node-exporter
    networks:
      - monitoring

  pull-container:
    restart: always
    build:
      context: ./pull-container
      dockerfile: Dockerfile
    networks:
      - monitoring

  push-container:
    restart: always
    build:
      context: ./push-container
      dockerfile: Dockerfile
    depends_on:
      - pushgateway
    networks:
      - monitoring
