version: '2'

networks:
  monitoring:

services:
  grafana:
    restart: always
    image: grafana/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring
    ports:
      - 3000:3000

  prometheus:
    restart: always
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    depends_on:
      - node-exporter
      - pull-container
    networks:
      - monitoring
    ports:
      - 9090:9090

  pushgateway:
    restart: always
    image: prom/pushgateway
    depends_on:
      - prometheus
    networks:
      - monitoring
    ports:
      - 9091:9091

  node-exporter:
    restart: always
    image: prom/node-exporter
    networks:
      - monitoring
    ports:
      - 9100:9100

  pull-container:
    restart: always
    build:
      context: ./pull-container
      dockerfile: Dockerfile
    networks:
      - monitoring
    ports:
      - 8000:8000

  push-container:
    restart: always
    build:
      context: ./push-container
      dockerfile: Dockerfile
    depends_on:
      - pushgateway
    networks:
      - monitoring
